- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/monitoreo-elecciones-2021/monitoreo-elecciones:$SHORT_SHA', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/monitoreo-elecciones-2021/monitoreo-elecciones:$SHORT_SHA']